const mongoose = require("mongoose");
const slugify = require("slugify");
const Product = require("../models/productModel");
const Category = require("../models/prodcategoryModel");

const mongoUrl = process.env.MONGODB_URL || "mongodb://127.0.0.1:27017/full_mern_ecommerce";

const products = [
  { title: "Apple iPhone 15 Pro Max", description: "A17 Pro, premium camera, titanium build.", price: 149900, category: "Electronics", brand: "Apple", quantity: 18, tags: "featured", totalrating: 5, images: [{ public_id: "seed-iphone15", url: "https://images.unsplash.com/photo-1695048133142-1a20484d7d2b?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Samsung Galaxy S24 Ultra", description: "Flagship Android with S Pen and 200MP camera.", price: 129900, category: "Electronics", brand: "Samsung", quantity: 22, tags: "featured", totalrating: 5, images: [{ public_id: "seed-s24", url: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Sony WH-1000XM5", description: "Premium ANC wireless headphones.", price: 29990, category: "Audio", brand: "Sony", quantity: 35, tags: "featured", totalrating: 4, images: [{ public_id: "seed-sony", url: "https://images.unsplash.com/photo-1516110833967-0b5716ca1387?auto=format&fit=crop&w=900&q=80" }] },
  { title: "MacBook Air M3", description: "Lightweight laptop with excellent battery life.", price: 114900, category: "Computers", brand: "Apple", quantity: 14, tags: "featured", totalrating: 5, images: [{ public_id: "seed-mba", url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Dell XPS 13", description: "Compact premium ultrabook.", price: 89990, category: "Computers", brand: "Dell", quantity: 16, tags: "new", totalrating: 4, images: [{ public_id: "seed-xps", url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Canon EOS R6", description: "Full-frame mirrorless camera for creators.", price: 189900, category: "Cameras", brand: "Canon", quantity: 9, tags: "featured", totalrating: 5, images: [{ public_id: "seed-r6", url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Nike Air Max 270", description: "Comfortable everyday sneakers.", price: 12999, category: "Fashion", brand: "Nike", quantity: 45, tags: "popular", totalrating: 4, images: [{ public_id: "seed-airmax", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Adidas Training Hoodie", description: "Soft hoodie for gym and casual wear.", price: 4999, category: "Fashion", brand: "Adidas", quantity: 60, tags: "new", totalrating: 4, images: [{ public_id: "seed-hoodie", url: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Samsung 55-inch QLED TV", description: "4K smart television with HDR.", price: 75990, category: "Television", brand: "Samsung", quantity: 12, tags: "featured", totalrating: 5, images: [{ public_id: "seed-tv", url: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Fitbit Charge 6", description: "Fitness tracker with heart-rate and sleep tracking.", price: 16999, category: "Wearables", brand: "Fitbit", quantity: 28, tags: "popular", totalrating: 4, images: [{ public_id: "seed-fitbit", url: "https://images.unsplash.com/photo-1575311373937-040b8e1fd6b8?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Logitech MX Master 3S", description: "Ergonomic productivity mouse.", price: 9499, category: "Accessories", brand: "Logitech", quantity: 50, tags: "new", totalrating: 5, images: [{ public_id: "seed-mxmaster", url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Apple Watch Series 9", description: "Smartwatch with health and fitness features.", price: 45900, category: "Wearables", brand: "Apple", quantity: 25, tags: "featured", totalrating: 5, images: [{ public_id: "seed-watch9", url: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "OnePlus 12", description: "Flagship smartphone with Snapdragon 8 Gen 3.", price: 64999, category: "Electronics", brand: "OnePlus", quantity: 30, tags: "new", totalrating: 4, images: [{ public_id: "seed-oneplus12", url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80" }] },
  { title: "iPad Air 5", description: "Powerful and lightweight tablet for work and creativity.", price: 59900, category: "Electronics", brand: "Apple", quantity: 20, tags: "featured", totalrating: 5, images: [{ public_id: "seed-ipad-air", url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80" }] },
  { title: "boAt Airdopes 441", description: "True wireless earbuds with immersive bass.", price: 2499, category: "Audio", brand: "boAt", quantity: 80, tags: "popular", totalrating: 4, images: [{ public_id: "seed-airdopes", url: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f37?auto=format&fit=crop&w=900&q=80" }] },
  { title: "JBL Flip 6", description: "Portable Bluetooth speaker with deep sound.", price: 11999, category: "Audio", brand: "JBL", quantity: 40, tags: "new", totalrating: 4, images: [{ public_id: "seed-jbl-flip6", url: "https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=900&q=80" }] },
  { title: "HP Pavilion 15", description: "Reliable everyday laptop for students and professionals.", price: 67999, category: "Computers", brand: "HP", quantity: 26, tags: "popular", totalrating: 4, images: [{ public_id: "seed-hp-pavilion", url: "https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Lenovo IdeaPad Slim 5", description: "Slim performance laptop with long battery life.", price: 62999, category: "Computers", brand: "Lenovo", quantity: 24, tags: "new", totalrating: 4, images: [{ public_id: "seed-ideapad", url: "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "GoPro HERO11", description: "Action camera for travel, sports and vlogging.", price: 44990, category: "Cameras", brand: "GoPro", quantity: 15, tags: "featured", totalrating: 5, images: [{ public_id: "seed-gopro11", url: "https://images.unsplash.com/photo-1524143986875-3b098d78b363?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Puma Running Shoes", description: "Lightweight running shoes with cushioned sole.", price: 5799, category: "Fashion", brand: "Puma", quantity: 65, tags: "popular", totalrating: 4, images: [{ public_id: "seed-puma-shoes", url: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Levi's Denim Jacket", description: "Classic denim jacket for everyday style.", price: 4999, category: "Fashion", brand: "Levi's", quantity: 35, tags: "new", totalrating: 4, images: [{ public_id: "seed-denim-jacket", url: "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Nike Men's Dri-Fit T-Shirt", description: "Breathable men's performance t-shirt for active wear.", price: 1399, category: "Fashion", brand: "Nike", quantity: 120, tags: "popular", totalrating: 4, images: [{ public_id: "seed-men-nike-tshirt", url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Adidas Men's Essentials T-Shirt", description: "Soft cotton t-shirt for daily comfort.", price: 1199, category: "Fashion", brand: "Adidas", quantity: 130, tags: "new", totalrating: 4, images: [{ public_id: "seed-men-adidas-tshirt", url: "https://images.unsplash.com/photo-1583743814966-8936f37f4678?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Puma Men's Active T-Shirt", description: "Lightweight men's training t-shirt.", price: 1099, category: "Fashion", brand: "Puma", quantity: 110, tags: "special", totalrating: 4, images: [{ public_id: "seed-men-puma-tshirt", url: "https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Levi's Men's Logo T-Shirt", description: "Classic logo t-shirt with premium fabric.", price: 1499, category: "Fashion", brand: "Levi's", quantity: 95, tags: "featured", totalrating: 5, images: [{ public_id: "seed-men-levis-tshirt", url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Louis Philippe Men's Formal Shirt", description: "Elegant formal shirt tailored for office wear.", price: 2399, category: "Fashion", brand: "Louis Philippe", quantity: 80, tags: "featured", totalrating: 5, images: [{ public_id: "seed-men-lp-shirt", url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Allen Solly Men's Casual Shirt", description: "Smart casual shirt for everyday styling.", price: 1899, category: "Fashion", brand: "Allen Solly", quantity: 90, tags: "popular", totalrating: 4, images: [{ public_id: "seed-men-allen-shirt", url: "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Van Heusen Men's Slim Shirt", description: "Slim-fit shirt with wrinkle-resistant finish.", price: 2199, category: "Fashion", brand: "Van Heusen", quantity: 85, tags: "new", totalrating: 4, images: [{ public_id: "seed-men-vanheusen-shirt", url: "https://images.unsplash.com/photo-1594938328870-9623159c8c99?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Wrangler Men's Classic Jeans", description: "Durable denim jeans with straight fit.", price: 2499, category: "Fashion", brand: "Wrangler", quantity: 100, tags: "popular", totalrating: 4, images: [{ public_id: "seed-men-wrangler-jeans", url: "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Lee Men's Tapered Jeans", description: "Modern tapered jeans for a clean silhouette.", price: 2399, category: "Fashion", brand: "Lee", quantity: 95, tags: "special", totalrating: 4, images: [{ public_id: "seed-men-lee-jeans", url: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80" }] },
  { title: "H&M Men's Fleece Hoodie", description: "Warm fleece hoodie for casual layering.", price: 1999, category: "Fashion", brand: "H&M", quantity: 88, tags: "new", totalrating: 4, images: [{ public_id: "seed-men-hm-hoodie", url: "https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Nike Men's Zip Hoodie", description: "Comfortable zip hoodie with sporty look.", price: 2799, category: "Fashion", brand: "Nike", quantity: 82, tags: "featured", totalrating: 5, images: [{ public_id: "seed-men-nike-hoodie", url: "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Adidas Men's Pullover Hoodie", description: "Everyday pullover hoodie with soft lining.", price: 2599, category: "Fashion", brand: "Adidas", quantity: 86, tags: "popular", totalrating: 4, images: [{ public_id: "seed-men-adidas-hoodie", url: "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&w=900&q=80" }] },
  { title: "The North Face Men's Puffer Jacket", description: "Insulated puffer jacket for winter protection.", price: 6999, category: "Fashion", brand: "The North Face", quantity: 60, tags: "featured", totalrating: 5, images: [{ public_id: "seed-men-tnf-jacket", url: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Zara Men's Bomber Jacket", description: "Stylish bomber jacket for modern streetwear.", price: 5499, category: "Fashion", brand: "Zara", quantity: 68, tags: "new", totalrating: 4, images: [{ public_id: "seed-men-zara-jacket", url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Zara Women's Ribbed Top", description: "Slim-fit ribbed top for everyday wear.", price: 1499, category: "Fashion", brand: "Zara", quantity: 120, tags: "popular", totalrating: 4, images: [{ public_id: "seed-women-zara-top", url: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80" }] },
  { title: "H&M Women's Cotton Top", description: "Soft cotton top with relaxed fit.", price: 1299, category: "Fashion", brand: "H&M", quantity: 125, tags: "new", totalrating: 4, images: [{ public_id: "seed-women-hm-top", url: "https://images.unsplash.com/photo-1464863979621-258859e62245?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Forever 21 Women's Crop Top", description: "Trendy crop top for casual outings.", price: 999, category: "Fashion", brand: "Forever 21", quantity: 118, tags: "special", totalrating: 4, images: [{ public_id: "seed-women-forever21-top", url: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Mango Women's Floral Dress", description: "Elegant floral dress for day events.", price: 3299, category: "Fashion", brand: "Mango", quantity: 90, tags: "featured", totalrating: 5, images: [{ public_id: "seed-women-mango-dress", url: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Shein Women's Midi Dress", description: "Flowy midi dress with contemporary styling.", price: 1899, category: "Fashion", brand: "Shein", quantity: 105, tags: "popular", totalrating: 4, images: [{ public_id: "seed-women-shein-dress", url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80" }] },
  { title: "H&M Women's Summer Dress", description: "Light summer dress with breathable fabric.", price: 2199, category: "Fashion", brand: "H&M", quantity: 98, tags: "new", totalrating: 4, images: [{ public_id: "seed-women-hm-dress", url: "https://images.unsplash.com/photo-1469460340997-2f854421e72f?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Fabindia Silk Saree", description: "Traditional silk saree with rich detailing.", price: 4899, category: "Fashion", brand: "Fabindia", quantity: 70, tags: "featured", totalrating: 5, images: [{ public_id: "seed-women-fabindia-saree", url: "https://images.unsplash.com/photo-1610030469668-7d876c6f5e50?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Biba Designer Saree", description: "Designer saree for festive occasions.", price: 4299, category: "Fashion", brand: "Biba", quantity: 75, tags: "special", totalrating: 4, images: [{ public_id: "seed-women-biba-saree", url: "https://images.unsplash.com/photo-1610189020376-6b0f19ef8b9d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "W for Woman Printed Kurti", description: "Printed kurti with comfortable fit.", price: 1799, category: "Fashion", brand: "W for Woman", quantity: 112, tags: "popular", totalrating: 4, images: [{ public_id: "seed-women-w-kurti", url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Global Desi Ethnic Kurti", description: "Ethnic kurti for casual and festive looks.", price: 1699, category: "Fashion", brand: "Global Desi", quantity: 108, tags: "new", totalrating: 4, images: [{ public_id: "seed-women-globaldesi-kurti", url: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Levi's Women's Skinny Jeans", description: "Stretch denim skinny jeans for daily wear.", price: 2799, category: "Fashion", brand: "Levi's", quantity: 96, tags: "featured", totalrating: 5, images: [{ public_id: "seed-women-levis-jeans", url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Lee Women's Straight Jeans", description: "Classic straight-fit jeans with soft denim.", price: 2499, category: "Fashion", brand: "Lee", quantity: 94, tags: "popular", totalrating: 4, images: [{ public_id: "seed-women-lee-jeans", url: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Gini & Jony Kids T-Shirt", description: "Soft cotton t-shirt for kids.", price: 799, category: "Fashion", brand: "Gini & Jony", quantity: 150, tags: "popular", totalrating: 4, images: [{ public_id: "seed-kids-ginijony-tshirt", url: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80" }] },
  { title: "U.S. Polo Assn. Kids T-Shirt", description: "Comfort fit t-shirt with premium fabric.", price: 999, category: "Fashion", brand: "U.S. Polo Assn.", quantity: 140, tags: "new", totalrating: 4, images: [{ public_id: "seed-kids-uspolo-tshirt", url: "https://images.unsplash.com/photo-1503919005314-30d93d07d823?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Mothercare Kids Clothing Set", description: "Coordinated clothing set for toddlers.", price: 1599, category: "Fashion", brand: "Mothercare", quantity: 105, tags: "featured", totalrating: 5, images: [{ public_id: "seed-kids-mothercare-set", url: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Hopscotch Kids Clothing Set", description: "Stylish kids set for outings and occasions.", price: 1399, category: "Fashion", brand: "Hopscotch", quantity: 115, tags: "popular", totalrating: 4, images: [{ public_id: "seed-kids-hopscotch-set", url: "https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=900&q=80" }] },
  { title: "H&M Kids Hoodie", description: "Warm and cozy hoodie for kids.", price: 1499, category: "Fashion", brand: "H&M", quantity: 120, tags: "special", totalrating: 4, images: [{ public_id: "seed-kids-hm-hoodie", url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Zara Kids Hoodie", description: "Trendy hoodie with soft inner lining.", price: 1699, category: "Fashion", brand: "Zara Kids", quantity: 110, tags: "new", totalrating: 4, images: [{ public_id: "seed-kids-zarakids-hoodie", url: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Nike Lifestyle Sneakers", description: "Comfortable sneakers for daily use.", price: 4299, category: "Fashion", brand: "Nike", quantity: 100, tags: "featured", totalrating: 5, images: [{ public_id: "seed-footwear-nike-sneaker", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Adidas Run Sneakers", description: "Cushioned sneakers with responsive sole.", price: 3999, category: "Fashion", brand: "Adidas", quantity: 102, tags: "popular", totalrating: 4, images: [{ public_id: "seed-footwear-adidas-sneaker", url: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Puma Street Sneakers", description: "Street-style sneakers for casual outfits.", price: 3799, category: "Fashion", brand: "Puma", quantity: 98, tags: "new", totalrating: 4, images: [{ public_id: "seed-footwear-puma-sneaker", url: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Bata Formal Shoes", description: "Classic formal shoes for office and events.", price: 2899, category: "Fashion", brand: "Bata", quantity: 92, tags: "popular", totalrating: 4, images: [{ public_id: "seed-footwear-bata-formal", url: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Clarks Leather Formal Shoes", description: "Premium leather formal shoes with comfort sole.", price: 5499, category: "Fashion", brand: "Clarks", quantity: 70, tags: "featured", totalrating: 5, images: [{ public_id: "seed-footwear-clarks-formal", url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Hush Puppies Formal Shoes", description: "Elegant formal footwear with cushioned support.", price: 4999, category: "Fashion", brand: "Hush Puppies", quantity: 74, tags: "special", totalrating: 4, images: [{ public_id: "seed-footwear-hushpuppies-formal", url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Crocs Classic Sandals", description: "Lightweight sandals for all-day comfort.", price: 2499, category: "Fashion", brand: "Crocs", quantity: 130, tags: "new", totalrating: 4, images: [{ public_id: "seed-footwear-crocs-sandal", url: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Metro Shoes Sandals", description: "Stylish sandals for casual and festive looks.", price: 2199, category: "Fashion", brand: "Metro Shoes", quantity: 120, tags: "popular", totalrating: 4, images: [{ public_id: "seed-footwear-metro-sandal", url: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Steve Madden Women Heels", description: "Elegant heels for parties and formal events.", price: 4699, category: "Fashion", brand: "Steve Madden", quantity: 88, tags: "featured", totalrating: 5, images: [{ public_id: "seed-footwear-stevemadden-heels", url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Catwalk Women Heels", description: "Chic heels with comfortable block design.", price: 2999, category: "Fashion", brand: "Catwalk", quantity: 95, tags: "special", totalrating: 4, images: [{ public_id: "seed-footwear-catwalk-heels", url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Fastrack Analog Watch", description: "Trendy analog watch for daily wear.", price: 2199, category: "Fashion", brand: "Fastrack", quantity: 140, tags: "popular", totalrating: 4, images: [{ public_id: "seed-access-fastrack-watch", url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Titan Classic Watch", description: "Elegant watch with premium strap and dial.", price: 4299, category: "Fashion", brand: "Titan", quantity: 110, tags: "featured", totalrating: 5, images: [{ public_id: "seed-access-titan-watch", url: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Casio Digital Watch", description: "Durable digital watch for active lifestyle.", price: 2599, category: "Fashion", brand: "Casio", quantity: 125, tags: "new", totalrating: 4, images: [{ public_id: "seed-access-casio-watch", url: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Wildcraft Backpack", description: "Spacious backpack for travel and daily commute.", price: 1899, category: "Fashion", brand: "Wildcraft", quantity: 150, tags: "popular", totalrating: 4, images: [{ public_id: "seed-access-wildcraft-bag", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80" }] },
  { title: "American Tourister Travel Bag", description: "Durable travel bag with multiple compartments.", price: 3299, category: "Fashion", brand: "American Tourister", quantity: 100, tags: "featured", totalrating: 5, images: [{ public_id: "seed-access-americantourister-bag", url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Skybags Daypack", description: "Compact daypack for office and college use.", price: 1699, category: "Fashion", brand: "Skybags", quantity: 145, tags: "new", totalrating: 4, images: [{ public_id: "seed-access-skybags-bag", url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a45?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Ray-Ban Aviator Sunglasses", description: "Timeless aviator sunglasses with UV protection.", price: 5999, category: "Fashion", brand: "Ray-Ban", quantity: 85, tags: "featured", totalrating: 5, images: [{ public_id: "seed-access-rayban-sunglasses", url: "https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Fastrack Wayfarer Sunglasses", description: "Stylish wayfarer sunglasses for daily wear.", price: 1499, category: "Fashion", brand: "Fastrack", quantity: 130, tags: "popular", totalrating: 4, images: [{ public_id: "seed-access-fastrack-sunglasses", url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Levi's Leather Belt", description: "Premium leather belt for formal and casual wear.", price: 1299, category: "Fashion", brand: "Levi's", quantity: 140, tags: "new", totalrating: 4, images: [{ public_id: "seed-access-levis-belt", url: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Allen Solly Formal Belt", description: "Sleek formal belt with polished buckle.", price: 1199, category: "Fashion", brand: "Allen Solly", quantity: 135, tags: "special", totalrating: 4, images: [{ public_id: "seed-access-allensolly-belt", url: "https://images.unsplash.com/photo-1595341595379-cf0f0f6a7f01?auto=format&fit=crop&w=900&q=80" }] },
  { title: "LG 43-inch 4K Smart TV", description: "Ultra HD smart TV with vibrant picture quality.", price: 42990, category: "Television", brand: "LG", quantity: 18, tags: "featured", totalrating: 4, images: [{ public_id: "seed-lg-tv", url: "https://images.unsplash.com/photo-1461151304267-38535e780c79?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Noise ColorFit Pro 5", description: "Smartwatch with AMOLED display and health tracking.", price: 4999, category: "Wearables", brand: "Noise", quantity: 55, tags: "popular", totalrating: 4, images: [{ public_id: "seed-noise-watch", url: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Apple MagSafe Charger", description: "Fast and reliable magnetic wireless charging.", price: 4499, category: "Accessories", brand: "Apple", quantity: 70, tags: "new", totalrating: 5, images: [{ public_id: "seed-magsafe", url: "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?auto=format&fit=crop&w=900&q=80" }] },
  { title: "Anker 20W USB-C Adapter", description: "Compact fast charger for phones and tablets.", price: 1299, category: "Accessories", brand: "Anker", quantity: 90, tags: "popular", totalrating: 4, images: [{ public_id: "seed-anker-adapter", url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Basmati Rice 5kg", description: "Premium aged basmati rice for daily cooking.", price: 599, category: "Grocery", brand: "India Gate", quantity: 140, tags: "featured", totalrating: 5, images: [{ public_id: "seed-rice", url: "https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Sunflower Cooking Oil", description: "Refined cooking oil for everyday meals.", price: 279, category: "Grocery", brand: "Fortune", quantity: 180, tags: "popular", totalrating: 4, images: [{ public_id: "seed-oil", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Whole Wheat Atta 10kg", description: "Stone-ground wheat flour for soft rotis and bread.", price: 449, category: "Grocery", brand: "Aashirvaad", quantity: 160, tags: "new", totalrating: 5, images: [{ public_id: "seed-atta", url: "https://images.unsplash.com/photo-1608032077018-cf56f3a1f7f1?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Tomato Ketchup", description: "Classic tangy ketchup for snacks and meals.", price: 189, category: "Grocery", brand: "Kissan", quantity: 210, tags: "special", totalrating: 4, images: [{ public_id: "seed-ketchup", url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Green Gram Dal 1kg", description: "Protein-rich moong dal for everyday healthy meals.", price: 189, category: "Grocery", brand: "Tata Sampann", quantity: 170, tags: "popular", totalrating: 4, images: [{ public_id: "seed-moong-dal", url: "https://images.unsplash.com/photo-1586201375761-83865001e31f?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Toor Dal 1kg", description: "Quality toor dal with natural taste and aroma.", price: 209, category: "Grocery", brand: "Organic Tattva", quantity: 150, tags: "featured", totalrating: 5, images: [{ public_id: "seed-toor-dal", url: "https://images.unsplash.com/photo-1612257998512-6b3f35c59c7a?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Peanut Butter Crunchy", description: "High-protein crunchy peanut butter spread.", price: 325, category: "Grocery", brand: "Pintola", quantity: 130, tags: "new", totalrating: 4, images: [{ public_id: "seed-peanut-butter", url: "https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Raw Honey 500g", description: "Natural raw honey for daily wellness and sweetening.", price: 399, category: "Grocery", brand: "Dabur", quantity: 145, tags: "featured", totalrating: 5, images: [{ public_id: "seed-honey", url: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Premium Black Tea", description: "Strong aroma tea leaves for rich daily chai.", price: 249, category: "Grocery", brand: "Taj Mahal", quantity: 160, tags: "special", totalrating: 4, images: [{ public_id: "seed-black-tea", url: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Mixed Fruit Jam", description: "Sweet and fruity spread for bread and snacks.", price: 175, category: "Grocery", brand: "Kissan", quantity: 200, tags: "popular", totalrating: 4, images: [{ public_id: "seed-jam", url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Maybelline Fit Me Foundation", description: "Lightweight foundation for a natural matte finish.", price: 799, category: "Cosmetics", brand: "Maybelline", quantity: 120, tags: "featured", totalrating: 5, images: [{ public_id: "seed-foundation", url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "L'Oreal Paris Lipstick", description: "Highly pigmented creamy lipstick for daily wear.", price: 649, category: "Cosmetics", brand: "L'Oreal", quantity: 150, tags: "popular", totalrating: 4, images: [{ public_id: "seed-lipstick", url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Nivea Soft Moisturizing Cream", description: "Everyday moisturizing cream for face and body.", price: 299, category: "Cosmetics", brand: "Nivea", quantity: 200, tags: "special", totalrating: 4, images: [{ public_id: "seed-cream", url: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Lakme Eyeconic Kajal", description: "Long-lasting smudge-proof kajal pencil.", price: 349, category: "Cosmetics", brand: "Lakme", quantity: 180, tags: "popular", totalrating: 4, images: [{ public_id: "seed-kajal", url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "The Body Shop Tea Tree Face Wash", description: "Refreshing face wash for oily skin types.", price: 1095, category: "Cosmetics", brand: "The Body Shop", quantity: 95, tags: "new", totalrating: 4, images: [{ public_id: "seed-facewash", url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Lotus Herbal Sunscreen SPF 50", description: "Broad-spectrum daily sunscreen protection.", price: 499, category: "Cosmetics", brand: "Lotus", quantity: 140, tags: "featured", totalrating: 5, images: [{ public_id: "seed-sunscreen", url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "M.A.C. Matte Lip Pencil", description: "Smooth matte finish lip pencil with rich color.", price: 1890, category: "Cosmetics", brand: "MAC", quantity: 70, tags: "special", totalrating: 5, images: [{ public_id: "seed-lippencil", url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Himalaya Purifying Neem Face Pack", description: "Herbal face pack for clear and fresh skin.", price: 250, category: "Cosmetics", brand: "Himalaya", quantity: 160, tags: "popular", totalrating: 4, images: [{ public_id: "seed-facepack", url: "https://images.unsplash.com/photo-1629198735661-7b92f30f6d27?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Liquid Foundation", description: "Buildable foundation for smooth and even skin tone.", price: 899, category: "Beauty", brand: "Maybelline", quantity: 150, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-foundation", url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Compact Powder", description: "Lightweight compact powder for matte finish.", price: 399, category: "Beauty", brand: "Lakme", quantity: 170, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-compact", url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Cream Concealer", description: "Full-coverage concealer for dark spots and blemishes.", price: 499, category: "Beauty", brand: "L'Oreal", quantity: 145, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-concealer", url: "https://images.unsplash.com/photo-1631214540553-ff044a3ff1d4?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Rose Blush Palette", description: "Soft blush shades for natural cheek tint.", price: 549, category: "Beauty", brand: "Colorbar", quantity: 135, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-blush", url: "https://images.unsplash.com/photo-1583241800698-9d32fd70d66f?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Glow Highlighter Stick", description: "Creamy highlighter for radiant glow.", price: 599, category: "Beauty", brand: "Faces Canada", quantity: 120, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-highlighter", url: "https://images.unsplash.com/photo-1596704017254-9a85ebf2faba?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Waterproof Eyeliner", description: "Smudge-proof eyeliner for all-day wear.", price: 349, category: "Beauty", brand: "Lakme", quantity: 190, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-eyeliner", url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Volume Mascara", description: "Adds volume and curl to lashes instantly.", price: 499, category: "Beauty", brand: "Maybelline", quantity: 165, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-mascara", url: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Deep Black Kajal", description: "Intense black kajal with long-lasting formula.", price: 299, category: "Beauty", brand: "Lakme", quantity: 210, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-kajal", url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Velvet Matte Lipstick", description: "Highly pigmented matte lipstick for bold looks.", price: 699, category: "Beauty", brand: "MAC", quantity: 140, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-lipstick", url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Shine Lip Gloss", description: "Glossy finish lip gloss with moisturizing effect.", price: 349, category: "Beauty", brand: "Nykaa", quantity: 175, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-lipgloss", url: "https://images.unsplash.com/photo-1556229010-8f4f4f9b5f8e?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Nourishing Lip Balm", description: "Hydrating lip balm for dry and chapped lips.", price: 199, category: "Beauty", brand: "Nivea", quantity: 230, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-lipbalm", url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Gentle Face Wash", description: "Daily face wash for clean and fresh skin.", price: 299, category: "Beauty", brand: "Cetaphil", quantity: 190, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-facewash", url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Hydrating Cleanser", description: "Mild cleanser that removes dirt without dryness.", price: 499, category: "Beauty", brand: "CeraVe", quantity: 160, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-cleanser", url: "https://images.unsplash.com/photo-1619451334792-150fd785ee74?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Refreshing Toner", description: "Alcohol-free toner to tighten and refresh skin.", price: 399, category: "Beauty", brand: "Plum", quantity: 170, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-toner", url: "https://images.unsplash.com/photo-1571781565036-d3f759be73e4?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Daily Moisturizer", description: "Lightweight moisturizer for soft and smooth skin.", price: 449, category: "Beauty", brand: "Neutrogena", quantity: 200, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-moisturizer", url: "https://images.unsplash.com/photo-1599843241464-f6f5a29e558b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Ultra Shield Sunscreen", description: "SPF 50 sunscreen with broad-spectrum protection.", price: 599, category: "Beauty", brand: "Lotus", quantity: 175, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-sunscreen", url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Vitamin C Face Serum", description: "Brightening serum for glowing and even skin.", price: 799, category: "Beauty", brand: "Minimalist", quantity: 150, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-serum", url: "https://images.unsplash.com/photo-1620916297397-a4a5402a3fdf?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Hydra Sheet Masks Pack", description: "Hydrating sheet masks for instant skin revival.", price: 350, category: "Beauty", brand: "Innisfree", quantity: 180, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-sheetmasks", url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Exfoliating Face Scrub", description: "Gentle scrub to remove dead skin cells.", price: 329, category: "Beauty", brand: "Himalaya", quantity: 165, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-scrub", url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Repair Night Cream", description: "Nourishing night cream for overnight skin repair.", price: 699, category: "Beauty", brand: "Olay", quantity: 140, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-nightcream", url: "https://images.unsplash.com/photo-1607602132700-068258f8f3cc?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Under-Eye Cream", description: "Reduces puffiness and dark circles effectively.", price: 499, category: "Beauty", brand: "Mamaearth", quantity: 155, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-undereye", url: "https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Silk Body Lotion", description: "Deep hydration body lotion for all skin types.", price: 399, category: "Beauty", brand: "Nivea", quantity: 210, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-bodylotion", url: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Refreshing Body Wash", description: "Gentle body wash with refreshing fragrance.", price: 349, category: "Beauty", brand: "Dove", quantity: 200, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-bodywash", url: "https://images.unsplash.com/photo-1571781565036-d3f759be73e4?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Moisture Soap Bar", description: "Creamy soap bar that cleans and moisturizes.", price: 149, category: "Beauty", brand: "Dove", quantity: 260, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-soap", url: "https://images.unsplash.com/photo-1584305574647-acf8069a3d1b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Soft Hand Cream", description: "Quick-absorbing hand cream for soft hands.", price: 249, category: "Beauty", brand: "The Body Shop", quantity: 175, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-handcream", url: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Fresh Deodorant Spray", description: "Long-lasting deodorant for all-day freshness.", price: 299, category: "Beauty", brand: "Nivea", quantity: 230, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-deodorant", url: "https://images.unsplash.com/photo-1602183418796-0d89f6f8707f?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Floral Perfume", description: "Elegant floral perfume for everyday use.", price: 999, category: "Beauty", brand: "Yardley", quantity: 120, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-perfume", url: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Keratin Shampoo", description: "Repair shampoo for smooth and strong hair.", price: 499, category: "Beauty", brand: "Tresemme", quantity: 180, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-shampoo", url: "https://images.unsplash.com/photo-1626792206799-08c4cbf4a8a7?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Deep Care Conditioner", description: "Nourishing conditioner for manageable hair.", price: 449, category: "Beauty", brand: "Loreal", quantity: 170, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-conditioner", url: "https://images.unsplash.com/photo-1631730486784-1f8c8ae5f7c8?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Nourishing Hair Oil", description: "Hair oil for scalp nourishment and shine.", price: 299, category: "Beauty", brand: "Parachute", quantity: 210, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-hairoil", url: "https://images.unsplash.com/photo-1620906554970-2f2f5893d086?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Frizz Control Hair Serum", description: "Light serum to control frizz and add shine.", price: 549, category: "Beauty", brand: "Livon", quantity: 155, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-hairserum", url: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Protein Hair Mask", description: "Weekly repair mask for damaged hair.", price: 699, category: "Beauty", brand: "Mamaearth", quantity: 140, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-hairmask", url: "https://images.unsplash.com/photo-1523264766116-1f4f02f81462?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Strong Hold Hair Gel", description: "Non-sticky gel for long-lasting hairstyle hold.", price: 249, category: "Beauty", brand: "Set Wet", quantity: 190, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-hairgel", url: "https://images.unsplash.com/photo-1605497787865-e6cf4d389f3e?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Finishing Hair Spray", description: "Quick-dry hair spray for style lock.", price: 399, category: "Beauty", brand: "Schwarzkopf", quantity: 130, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-hairspray", url: "https://images.unsplash.com/photo-1620331311520-246422fd82f9?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Precision Razor", description: "Smooth glide razor for gentle grooming.", price: 199, category: "Beauty", brand: "Gillette", quantity: 240, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-razor", url: "https://images.unsplash.com/photo-1599351431403-9432f4f5f3c8?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Shaving Cream Foam", description: "Rich shaving cream for clean and close shave.", price: 249, category: "Beauty", brand: "Old Spice", quantity: 180, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-shavingcream", url: "https://images.unsplash.com/photo-1608466564474-f8f0f297f28e?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Aftershave Lotion Cool", description: "Soothing aftershave lotion with cooling effect.", price: 299, category: "Beauty", brand: "Nivea Men", quantity: 165, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-aftershave", url: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Beard Trimmer Pro", description: "Rechargeable trimmer with precision settings.", price: 1799, category: "Beauty", brand: "Philips", quantity: 120, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-trimmer", url: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Pure Aloe Vera Gel", description: "Multi-use soothing gel for skin and hair.", price: 249, category: "Beauty", brand: "Patanjali", quantity: 220, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-aloevera", url: "https://images.unsplash.com/photo-1629198728482-55e94f2e2c58?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Neem Face Pack Herbal", description: "Herbal neem pack for clear and fresh skin.", price: 229, category: "Beauty", brand: "Himalaya", quantity: 180, tags: "special", totalrating: 4, images: [{ public_id: "seed-beauty-neempack", url: "https://images.unsplash.com/photo-1629198735661-7b92f30f6d27?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Herbal Protein Shampoo", description: "Natural shampoo blend for healthy scalp and hair.", price: 369, category: "Beauty", brand: "Khadi", quantity: 165, tags: "new", totalrating: 4, images: [{ public_id: "seed-beauty-herbalshampoo", url: "https://images.unsplash.com/photo-1626792206799-08c4cbf4a8a7?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Virgin Coconut Oil", description: "Cold-pressed coconut oil for skin and hair care.", price: 349, category: "Beauty", brand: "Parachute", quantity: 175, tags: "featured", totalrating: 5, images: [{ public_id: "seed-beauty-coconutoil", url: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Multani Mitti Powder", description: "Fuller's earth powder for natural skin detox.", price: 179, category: "Beauty", brand: "Biotique", quantity: 200, tags: "popular", totalrating: 4, images: [{ public_id: "seed-beauty-multanimitti", url: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Iodized Salt", description: "Refined iodized salt for everyday cooking.", price: 30, category: "Grocery", brand: "Tata", quantity: 350, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-salt", url: "https://images.unsplash.com/photo-1518110925495-5fe2cbfb4b74?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Turmeric Powder", description: "Pure turmeric spice with rich color and aroma.", price: 85, category: "Grocery", brand: "Everest", quantity: 300, tags: "featured", totalrating: 4, images: [{ public_id: "seed-grocery-turmeric", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f8?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Red Chili Powder", description: "Hot and vibrant red chili powder for curries.", price: 95, category: "Grocery", brand: "MDH", quantity: 290, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-redchili", url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Cumin Seeds", description: "Aromatic jeera seeds for tempering and masalas.", price: 110, category: "Grocery", brand: "Catch", quantity: 250, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-cumin", url: "https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Coriander Powder", description: "Fresh ground coriander spice blend.", price: 78, category: "Grocery", brand: "Everest", quantity: 280, tags: "special", totalrating: 4, images: [{ public_id: "seed-grocery-coriander", url: "https://images.unsplash.com/photo-1609501676725-7186f73495d3?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Garam Masala", description: "Traditional aromatic garam masala blend.", price: 120, category: "Grocery", brand: "MDH", quantity: 240, tags: "featured", totalrating: 4, images: [{ public_id: "seed-grocery-garammasala", url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Mustard Seeds", description: "Premium mustard seeds for seasoning.", price: 65, category: "Grocery", brand: "24 Mantra", quantity: 220, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-mustard", url: "https://images.unsplash.com/photo-1615485291234-9ea5a7c4f4ea?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Black Pepper Whole", description: "Whole black pepper for bold flavor.", price: 140, category: "Grocery", brand: "Catch", quantity: 210, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-blackpepper", url: "https://images.unsplash.com/photo-1541726260-e8b6f8f4f236?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Groundnut Oil", description: "Filtered groundnut oil for frying and cooking.", price: 310, category: "Grocery", brand: "Fortune", quantity: 230, tags: "featured", totalrating: 4, images: [{ public_id: "seed-grocery-groundnutoil", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Coconut Cooking Oil", description: "Pure coconut oil suitable for cooking.", price: 340, category: "Grocery", brand: "Parachute", quantity: 200, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-coconutoil", url: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Mustard Cooking Oil", description: "Strong flavor mustard oil for traditional dishes.", price: 285, category: "Grocery", brand: "Dhara", quantity: 210, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-mustardoil", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Olive Oil Extra Virgin", description: "Extra virgin olive oil for salads and light cooking.", price: 699, category: "Grocery", brand: "Borges", quantity: 165, tags: "special", totalrating: 5, images: [{ public_id: "seed-grocery-oliveoil", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Cow Ghee", description: "Rich and aromatic ghee for cooking and sweets.", price: 560, category: "Grocery", brand: "Amul", quantity: 190, tags: "featured", totalrating: 5, images: [{ public_id: "seed-grocery-ghee", url: "https://images.unsplash.com/photo-1627485937980-221c88ac04f9?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Butter Biscuits", description: "Crispy butter biscuits for tea-time snacks.", price: 60, category: "Grocery", brand: "Britannia", quantity: 350, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-biscuits", url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Potato Chips", description: "Crispy salted chips snack pack.", price: 40, category: "Grocery", brand: "Lays", quantity: 420, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-chips", url: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Instant Noodles", description: "Quick-cook masala noodles.", price: 55, category: "Grocery", brand: "Maggi", quantity: 390, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-noodles", url: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Durum Wheat Pasta", description: "Pasta made with durum wheat semolina.", price: 115, category: "Grocery", brand: "Saffola", quantity: 260, tags: "special", totalrating: 4, images: [{ public_id: "seed-grocery-pasta", url: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Instant Tomato Soup", description: "Ready-to-make tomato soup sachets.", price: 90, category: "Grocery", brand: "Knorr", quantity: 230, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-soup", url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Milk Chocolate Bar", description: "Creamy milk chocolate bar.", price: 80, category: "Grocery", brand: "Cadbury", quantity: 340, tags: "featured", totalrating: 5, images: [{ public_id: "seed-grocery-chocolates", url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Premium Tea", description: "Strong and aromatic tea blend.", price: 220, category: "Grocery", brand: "Brooke Bond", quantity: 270, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-tea", url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Instant Coffee", description: "Rich instant coffee granules.", price: 320, category: "Grocery", brand: "Nescafe", quantity: 240, tags: "featured", totalrating: 5, images: [{ public_id: "seed-grocery-coffee", url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Mixed Fruit Juice", description: "Ready-to-drink mixed fruit juice.", price: 120, category: "Grocery", brand: "Real", quantity: 250, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-juice", url: "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Sparkling Soft Drink", description: "Chilled carbonated soft drink.", price: 45, category: "Grocery", brand: "Coca-Cola", quantity: 410, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-softdrink", url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Energy Drink Can", description: "Energy drink for instant refreshment.", price: 125, category: "Grocery", brand: "Red Bull", quantity: 220, tags: "special", totalrating: 4, images: [{ public_id: "seed-grocery-energy", url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Detergent Powder", description: "Powerful detergent powder for stain removal.", price: 240, category: "Grocery", brand: "Surf Excel", quantity: 280, tags: "featured", totalrating: 4, images: [{ public_id: "seed-grocery-detergent", url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Dishwashing Liquid", description: "Concentrated dishwash liquid for clean utensils.", price: 110, category: "Grocery", brand: "Vim", quantity: 300, tags: "popular", totalrating: 4, images: [{ public_id: "seed-grocery-dishwash", url: "https://images.unsplash.com/photo-1581578021682-2d0f6f741f62?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Antibacterial Cleaning Spray", description: "Multipurpose surface cleaning spray.", price: 190, category: "Grocery", brand: "Lizol", quantity: 250, tags: "new", totalrating: 4, images: [{ public_id: "seed-grocery-cleaningspray", url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Bath Soap Pack", description: "Mild bath soap for daily use.", price: 95, category: "Grocery", brand: "Lux", quantity: 320, tags: "special", totalrating: 4, images: [{ public_id: "seed-grocery-soap", url: "https://images.unsplash.com/photo-1584305574647-acf8069a3d1b?auto=format&fit=crop&w=900&q=80" }] }
  ,{ title: "Whitening Toothpaste", description: "Fluoride toothpaste for cavity protection.", price: 120, category: "Grocery", brand: "Colgate", quantity: 330, tags: "featured", totalrating: 4, images: [{ public_id: "seed-grocery-toothpaste", url: "https://images.unsplash.com/photo-1559591935-c6cb7f4f35fb?auto=format&fit=crop&w=900&q=80" }] }
];

async function seed() {
  await mongoose.connect(mongoUrl);
  const uniqueCategories = [...new Set(products.map((item) => item.category))];

  for (const categoryTitle of uniqueCategories) {
    const categorySlug = slugify(categoryTitle, { lower: true });
    await Category.findOneAndUpdate(
      { title: categoryTitle },
      { title: categoryTitle, slug: categorySlug },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
  }
  let inserted = 0;
  let skipped = 0;

  for (const item of products) {
    const slug = slugify(item.title, { lower: true });
    const existing = await Product.findOne({ slug });
    if (existing) {
      skipped += 1;
      continue;
    }
    await Product.create({ ...item, slug });
    inserted += 1;
  }

  console.log(`Seed complete. Inserted ${inserted}, skipped ${skipped}.`);
  await mongoose.disconnect();
}

seed().catch(async (err) => {
  console.error(err);
  await mongoose.disconnect().catch(() => {});
  process.exit(1);
});
